global:
  scrape_interval: 5s
  external_labels:
    monitor: 'monitor'
scrape_configs:
  - job_name: 'node_exporter'
    static_configs: 
      - targets: ['192.168.99.11:9100']
      - targets: ['192.168.99.12:9100']
      - targets: ['192.168.99.13:9100']

  - job_name: 'kafka_brokers'
    static_configs:
      - targets: ['192.168.99.11:7071']
      - targets: ['192.168.99.12:7071']
      - targets: ['192.168.99.13:7071']
