- name: Install dependencies
  apt:
    pkg:
      - vim
      - tmux
      - htop
      - python3-apt
      - python3-docker
      - ca-certificates
      - wget
      - curl
      - docker.io
    update_cache: yes
