---
- hosts: prod
  become: yes
  vars:
    ver: 2.7.0
    env: prod
    zookeeper_port: 12181
    zookeeper_election: 12888:13888
    zookeeper_user: ZOOADMINUSER
    zookeeper_pass: ZOOADMINPASS

  tasks:
    - include_tasks: tasks/dependencies.yaml
    - include_tasks: tasks/system.yaml
    - include_tasks: tasks/zookeeper.yaml