---
- hosts: local
  become: yes
  vars:
    ver: 2.4.0
    env: local
    zookeeper_port: 12181
    zookeeper_user: LOCALADMINUSER
    zookeeper_pass: LOCALADMINPASS
    kafka_user: LOCALADMINUSER
    kafka_pass: LOCALADMINPASS

  tasks:

    - name: Install dependencies
      apt:
        pkg:
          - vim
          - tmux
          - python3-apt
          - python3-docker
          - ca-certificates
          - wget
          - curl
          - docker.io
        update_cache: yes
      when:
        inventory_hostname == "kafka-node1"

    - name: Create Zookeeper dirs
      file:
        path: "/opt/zookeeper-{{ env }}/{{ item }}"
        owner: root
        group: root
        mode: 0644
        state: directory
      loop:
        - data/zookeeper
        - config
        - logs

    - name: Copy Zookeeper JAAS config
      template:
        src: "templates/zookeeper_jaas.conf.j2"
        dest: "/opt/zookeeper-{{ env }}/config/zookeeper_jaas.conf"

    - name: Copy Zookeeper config
      template:
        src: "templates/zookeeper_local.properties.j2"
        dest: "/opt/zookeeper-{{ env }}/config/zookeeper.properties"

    - name: Copy Zookeeper id
      template:
        src: "templates/myid.j2"
        dest: "/opt/zookeeper-{{ env }}/data/zookeeper/myid"

    - name: Copy Zookeeper service file
      template:
        src: "templates/zookeeper.service.j2"
        dest: "/etc/systemd/system/zookeeper-{{ env }}.service"

    - name: Pull Zookeeper image
      docker_image:
        name: iaroki/zookeeper
        tag: "{{ ver }}"
        source: pull
        state: present

    - name: Start Zookeeper service
      systemd:
        name: "zookeeper-{{ env }}.service"
        state: started
        enabled: yes
        daemon_reload: yes

    - name: Create Kafka dirs
      file:
        path: "/opt/kafka-{{ env }}-{{ kafka_id }}/{{ item }}"
        owner: root
        group: root
        mode: 0644
        state: directory
      loop:
        - data
        - config
        - logs

    - name: Copy Kafka JAAS config
      template:
        src: "templates/kafka_jaas.conf.j2"
        dest: "/opt/kafka-{{ env }}-{{ kafka_id }}/config/kafka_jaas.conf"

    - name: Copy Kafka config
      template:
        src: "templates/server_local.properties.j2"
        dest: "/opt/kafka-{{ env }}-{{ kafka_id }}/config/server.properties"

    - name: Copy Kafka service file
      template:
        src: "templates/kafka_local.service.j2"
        dest: "/etc/systemd/system/kafka-{{ env }}-{{ kafka_id }}.service"

    - name: Pull Kafka image
      docker_image:
        name: iaroki/kafka
        tag: "{{ ver }}"
        source: pull
        state: present

    - name: Start Kafka service
      systemd:
        name: "kafka-{{ env }}-{{ kafka_id }}.service"
        state: started
        enabled: yes
        daemon_reload: yes
