Vagrant.configure(2) do |config|
  config.vm.box = "bento/debian-10"
  config.vm.box_check_update = false

  (1..3).each do |i|
    config.vm.define "broker#{i}" do |node|
      node.vm.hostname = "broker#{i}"
      node.vm.network "private_network", ip: "192.168.99.1#{i}"
      node.vm.provider "virtualbox" do |vb|
        vb.name = "broker#{i}"
        vb.cpus = 1
        vb.memory = 2048
      end
    end
  end
end
